### ISSUE TITLE
Can't be compiled without custom appmanifest

### ISSUE THREAD

**Issue by aglitchman** [defold/extension-vulkan#3]
The project can be compiled only with custom [generated appmanifest](https://britzl.github.io/manifestation/). Otherwise I'm getting this error:

![image](https://user-images.githubusercontent.com/193258/88153813-9767eb80-cc0e-11ea-9a05-f2017ae8ce4e.png)

**Comment by britzl** [comment]
Which version of Defold are you using?

**Comment by aglitchman** [comment]
<table>
<tr><td>Build time</td><td>2020-07-20T08:44:23.592964</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a98007b48691529b59fb099fc369d81518059d00</td></tr>
<tr><td>Defold engine sha</td><td>29b8e598b0bce19b274327c5d9711f78b3bd0c22</td></tr>
<tr><td>Defold version</td><td>1.2.171</td></tr>
<tr><td>GPU</td><td>GeForce RTX 2080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 451.48</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by ConnorHalford** [comment]
This is still an issue on Defold 1.1.180 and extension version 1.1.0. Specifically the Vulkan extension only compiles with a custom manifest with the 'Use Vulkan' setting. The 'Use OpenGL' or 'Use Vulkan and OpenGL' settings produce the errors above

**Comment by britzl** [comment]
We'll look into this soon.

**Comment by Jhonnyg** [comment]
This extension is deprecated, use the app manifest instead to select the backend(s) you want:
<img width="1142" alt="image" src="https://github.com/defold/extension-vulkan/assets/169640/34c73f6c-c596-4aca-b0aa-3ae3e6ec6963">
