### ISSUE TITLE
Make disabling Vulkan a game.project option for users in case they have a system reason to disable Vulkan

### ISSUE THREAD

**Issue by subsoap** [defold/extension-vulkan#4]
This is based on experience watching some streamers playing games with Vulkan support, occasionally issues happen with Vulkan and their setup, and so it would be good to have an option to be able to manually disable using it vs OpenGL in the game.project file at the very least. 

Ideally though it could be something set on render script init so that we could add options to disable it in game options screen for appropriate platforms. Along with that would need functions to check which render is being currently used / possibly swap them at runtime.

**Comment by britzl** [comment]
Yes, we have discussed how to make this into an option that could be toggled at engine startup, either as a command line argument or a game.project config value. It's on our list of things but not sure when and how this will be implemented yet.

@Jhonnyg and @JCash, any feedback?

**Comment by subsoap** [comment]
We'll be releasing our next game in September and I'll have Vulkan enabled for it. We'll be testing it with Vulkan enabled with users this month. If no issues come up we'll release it as is but I still anticipate it could be an issue with enough people playing.

**Comment by subsoap** [comment]
This already exists I think? Users should be able to edit the game.projectc and modify it to this, or delete those lines entirely to disable Vulkan?

```
[shader]
output_spirv = 0
```

**Comment by JCash** [comment]
I'm reluctant to reuse a variable like that, since it's very badly named in that case.

As for the actual feature request, I can see the benefit since we haven't got much mileage in the vulkan backend yet.
So, I'm for this addition (basically setting the prio of the interfaces)

```
[graphics]
adapter_prio = GraphicsAdapterOpenGL,GraphicsAdapterVulkan
```
will try the the OpenGL adaper first, then fallback to Vulkan.
Remember that we can pass project settings as command line parameters.
