### ISSUE TITLE
Vulkan can not do more than 256 draw calls (batches)

### ISSUE THREAD

**Issue by aglitchman** [defold/extension-vulkan#7]
I expected that we shouldn't see any difference in behavior between Vulkan and OpenGL.

I'm getting this error after spawning more than 250 meshes = 250 draw calls (+ some draw calls are used for GUI):
```
INFO:GRAPHICS: Created new VK Pipeline with hash 628706159170948476
INFO:GRAPHICS: Created new VK Pipeline with hash 8227808835322440851
Assertion failed: vk_descriptor_pool_out && *vk_descriptor_pool_out == VK_NULL_HANDLE, file ..\src\vulkan\graphics_vulkan_device.cpp, line 397
```

Test project is here: https://github.com/aglitchman/defold-vulkan-test

<table>
<tr><td>Build time</td><td>2020-08-03T06:59:58.950487</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>3bd2324df24700f072c380dc0ad9f58d6ac33ab3</td></tr>
<tr><td>Defold engine sha</td><td>3bd2324df24700f072c380dc0ad9f58d6ac33ab3</td></tr>
<tr><td>Defold version</td><td>1.2.172</td></tr>
<tr><td>GPU</td><td>GeForce RTX 2080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 451.48</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10 <b>Pro, version 2004</b></td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Jhonnyg** [comment]
This should be fixed now.
